Support custom QS for prefetches
blb-ventures/strawberry-django-plus pull request #212
Opened 2023-05-26 08:56 UTC by moritz89

Why:

- Repect the filters applied by get_queryset used in Django types

This change addresses the need by:

- Adding the option to keep the existing prefetch behavior
- Or prefetch witha the user's get_queryset and custom model manager

2023-05-26 09:01 UTC, moritz89 commented
Just checked that existing tests pass. If the general approach looks good, I'd also write a unit test. Some open points are probably:

- Checking that it works for select_related optimizations
- If the private typing function works across versions
- If this is the cleanest approach is dealing with ForwardRefs
- Add documentation / examples

2023-05-26 14:05 UTC, bellini666 requested changes
This seems mostly fine! :)

Just a couple of suggestions

2023-05-27 15:26 UTC, bellini666 approved these changes

2023-05-27 15:27 UTC, bellini666 commented
This is fine to merge IMO. I'll wait for you to remove it from draft

2023-05-27 15:40 UTC, moritz89 commented
Cool. I'll run a few more tests against it and set it as ready if nothing else crops up

2023-05-29 13:52 UTC, bellini666 commented
There are some pyright issues missing

obs. I'll separate the pyright test from the tests itself to make they run independently from one another

2023-05-29 15:40 UTC, moritz89 commented
Tried adding django_stubs to resolve `_base_manager`, but it only resulted in more errors :sweat_smile:

2023-05-29 15:45 UTC, bellini666 commented
> Tried adding django_stubs to resolve `_base_manager`, but it only resulted in more errors sweat_smile

This project has [django-types](https://github.com/sbdchd/django-types) in its dev dependencies, but it is missing typing for `_base_manager`, meaning we currently have to `# type: ingore` it =P

2023-05-29 15:54 UTC, bellini666 approved these changes

2023-05-29 15:54 UTC, merged